# Generated by Django 4.0.1 on 2022-02-02 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_alter_project_github_usernames"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="status",
            field=models.CharField(default="", max_length=255),
        ),
    ]
