# Generated by Django 4.0.3 on 2022-04-05 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_project_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="pro_private_key",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="project",
            name="pro_public_key",
            field=models.TextField(blank=True),
        ),
    ]
