# Generated by Django 4.0.5 on 2022-06-23 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_remove_project_pro_private_key_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-name']},
        ),
    ]
