# Generated by Django 4.1.5 on 2023-02-01 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0012_alter_project_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["name"]},
        ),
    ]
