# Generated by Django 4.0.5 on 2022-06-22 20:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_uuid_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="packages_token",
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
